version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wordbank
    ports:
      - "5431:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
