version: '3'
services:
  api:
    image: anderhi/wordbank
    ports:
    - 8080:8080
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wordbank
      - PGUSER=postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5