[package]
name = "cli"
version = "0.1.0"
authors = ["Anders Hallem Iversen <andershallemiversen@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
clap = "2.32"
