[package]
authors = ["Anders Hallem Iversen <andershallemiversen@hotmail.com>"]
edition = "2018"
name = "cli"
version = "0.1.0"

[dependencies]
lib = { path = "../lib" }
clap = "2.32"
directories = "4.0.1"
dotenv = "0.15.0"
serde = { version = "1.0.130", features = ["derive"]}
toml = "0.5.8"